DROP DATABASE mrmeetings;

CREATE DATABASE mrmeetings;

USE mrmeetings;


CREATE TABLE User (
    id INT(10) NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE Schedule (
    id INT NOT NULL AUTO_INCREMENT,
    id_user INT NOT NULL,
    monday_6 INT(2) DEFAULT 1,
    monday_7 INT(2) DEFAULT 1,
    monday_8 INT(2) DEFAULT 1,
    monday_9 INT(2) DEFAULT 1,
    monday_10 INT(2) DEFAULT 1,
    monday_11 INT(2) DEFAULT 1,
    monday_12 INT(2) DEFAULT 1,
    monday_13 INT(2) DEFAULT 1,
    monday_14 INT(2) DEFAULT 1,
    monday_15 INT(2) DEFAULT 1,
    monday_16 INT(2) DEFAULT 1,    
    monday_17 INT(2) DEFAULT 1,
    monday_18 INT(2) DEFAULT 1,
    monday_19 INT(2) DEFAULT 1,
    monday_20 INT(2) DEFAULT 1,
    monday_21 INT(2) DEFAULT 1,
    monday_22 INT(2) DEFAULT 1,
    monday_23 INT(2) DEFAULT 1,
    tuesday_6 INT(2) DEFAULT 1,
    tuesday_7 INT(2) DEFAULT 1,
    tuesday_8 INT(2) DEFAULT 1,
    tuesday_9 INT(2) DEFAULT 1,
    tuesday_10 INT(2) DEFAULT 1,
    tuesday_11 INT(2) DEFAULT 1,
    tuesday_12 INT(2) DEFAULT 1,
    tuesday_13 INT(2) DEFAULT 1,
    tuesday_14 INT(2) DEFAULT 1,
    tuesday_15 INT(2) DEFAULT 1,
    tuesday_16 INT(2) DEFAULT 1,
    tuesday_17 INT(2) DEFAULT 1,
    tuesday_18 INT(2) DEFAULT 1,
    tuesday_19 INT(2) DEFAULT 1,
    tuesday_20 INT(2) DEFAULT 1,
    tuesday_21 INT(2) DEFAULT 1,
    tuesday_22 INT(2) DEFAULT 1,
    tuesday_23 INT(2) DEFAULT 1,
    wednesday_6 INT(2) DEFAULT 1,
    wednesday_7 INT(2) DEFAULT 1,
    wednesday_8 INT(2) DEFAULT 1,
    wednesday_9 INT(2) DEFAULT 1,
    wednesday_10 INT(2) DEFAULT 1,
    wednesday_11 INT(2) DEFAULT 1,
    wednesday_12 INT(2) DEFAULT 1,
    wednesday_13 INT(2) DEFAULT 1,
    wednesday_14 INT(2) DEFAULT 1,
    wednesday_15 INT(2) DEFAULT 1,
    wednesday_16 INT(2) DEFAULT 1,
    wednesday_17 INT(2) DEFAULT 1,
    wednesday_18 INT(2) DEFAULT 1,
    wednesday_19 INT(2) DEFAULT 1,
    wednesday_20 INT(2) DEFAULT 1,
    wednesday_21 INT(2) DEFAULT 1,
    wednesday_22 INT(2) DEFAULT 1,
    wednesday_23 INT(2) DEFAULT 1,
    thursday_6 INT(2) DEFAULT 1,
    thursday_7 INT(2) DEFAULT 1,
    thursday_8 INT(2) DEFAULT 1,
    thursday_9 INT(2) DEFAULT 1,
    thursday_10 INT(2) DEFAULT 1,
    thursday_11 INT(2) DEFAULT 1,
    thursday_12 INT(2) DEFAULT 1,
    thursday_13 INT(2) DEFAULT 1,
    thursday_14 INT(2) DEFAULT 1,
    thursday_15 INT(2) DEFAULT 1,
    thursday_16 INT(2) DEFAULT 1,
    thursday_17 INT(2) DEFAULT 1,
    thursday_18 INT(2) DEFAULT 1,
    thursday_19 INT(2) DEFAULT 1,
    thursday_20 INT(2) DEFAULT 1,
    thursday_21 INT(2) DEFAULT 1,
    thursday_22 INT(2) DEFAULT 1,
    thursday_23 INT(2) DEFAULT 1,
    friday_6 INT(2) DEFAULT 1,
    friday_7 INT(2) DEFAULT 1,
    friday_8 INT(2) DEFAULT 1,
    friday_9 INT(2) DEFAULT 1,
    friday_10 INT(2) DEFAULT 1,
    friday_11 INT(2) DEFAULT 1,
    friday_12 INT(2) DEFAULT 1,
    friday_13 INT(2) DEFAULT 1,
    friday_14 INT(2) DEFAULT 1,
    friday_15 INT(2) DEFAULT 1,
    friday_16 INT(2) DEFAULT 1,
    friday_17 INT(2) DEFAULT 1,
    friday_18 INT(2) DEFAULT 1,
    friday_19 INT(2) DEFAULT 1,
    friday_20 INT(2) DEFAULT 1,
    friday_21 INT(2) DEFAULT 1,
    friday_22 INT(2) DEFAULT 1,
    friday_23 INT(2) DEFAULT 1,
    saturday_6 INT(2) DEFAULT 1,
    saturday_7 INT(2) DEFAULT 1,
    saturday_8 INT(2) DEFAULT 1,
    saturday_9 INT(2) DEFAULT 1,
    saturday_10 INT(2) DEFAULT 1,
    saturday_11 INT(2) DEFAULT 1,
    saturday_12 INT(2) DEFAULT 1,
    saturday_13 INT(2) DEFAULT 1,
    saturday_14 INT(2) DEFAULT 1,
    saturday_15 INT(2) DEFAULT 1,
    saturday_16 INT(2) DEFAULT 1,
    saturday_17 INT(2) DEFAULT 1,
    saturday_18 INT(2) DEFAULT 1,
    saturday_19 INT(2) DEFAULT 1,
    saturday_20 INT(2) DEFAULT 1,
    saturday_21 INT(2) DEFAULT 1,
    saturday_22 INT(2) DEFAULT 1,
    saturday_23 INT(2) DEFAULT 1,
    sunday_6 INT(2) DEFAULT 1,
    sunday_7 INT(2) DEFAULT 1,
    sunday_8 INT(2) DEFAULT 1,
    sunday_9 INT(2) DEFAULT 1,
    sunday_10 INT(2) DEFAULT 1,
    sunday_11 INT(2) DEFAULT 1,
    sunday_12 INT(2) DEFAULT 1,
    sunday_13 INT(2) DEFAULT 1,
    sunday_14 INT(2) DEFAULT 1,
    sunday_15 INT(2) DEFAULT 1,
    sunday_16 INT(2) DEFAULT 1,
    sunday_17 INT(2) DEFAULT 1,
    sunday_18 INT(2) DEFAULT 1,
    sunday_19 INT(2) DEFAULT 1,
    sunday_20 INT(2) DEFAULT 1,
    sunday_21 INT(2) DEFAULT 1,
    sunday_22 INT(2) DEFAULT 1,
    sunday_23 INT(2) DEFAULT 1,
    PRIMARY KEY (id),
    FOREIGN KEY (id_user) REFERENCES User(id)
);

CREATE TABLE Team (
    id INT(10) NOT NULL AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    id_user1 INT(10) NOT NULL,
    id_user2 INT(10) NOT NULL,
    id_user3 INT(10),
    id_user4 INT(10),
    id_user5 INT(10),
    id_user6 INT(10),   
    id_user7 INT(10),
    id_user8 INT(10),
    id_user9 INT(10),
    id_user10 INT(10),
    PRIMARY KEY (id),
    FOREIGN KEY (id_user1) REFERENCES User(id),
    FOREIGN KEY (id_user2) REFERENCES User(id),
    FOREIGN KEY (id_user3) REFERENCES User(id),
    FOREIGN KEY (id_user4) REFERENCES User(id),
    FOREIGN KEY (id_user5) REFERENCES User(id),
    FOREIGN KEY (id_user6) REFERENCES User(id),
    FOREIGN KEY (id_user7) REFERENCES User(id),
    FOREIGN KEY (id_user8) REFERENCES User(id),
    FOREIGN KEY (id_user9) REFERENCES User(id),
    FOREIGN KEY (id_user10) REFERENCES User(id)
    
);

CREATE TABLE Notification(
    id INT NOT NULL AUTO_INCREMENT,
    note VARCHAR(100) NOT NULL,
    status BOOLEAN NOT NULL,
    id_team INT(10),
    FOREIGN KEY (id_team) REFERENCES Team(id),
    PRIMARY KEY (id)
);

